### ISSUE TITLE
Access Workload Kind value in provisioners

### ISSUE THREAD

**Issue by maxstepanov** [score-spec/score-k8s#29]
I'd like my provisioners to make decisions based on Workload Kind being generated.

Looks like it's not present the Input struct

https://github.com/score-spec/score-k8s/blob/26e22116f2a7562d669256bc1d64e9013a6be346/internal/provisioners/core.go#L33-L59

May be it's possible to add `WorkloadKind` to the Input struct?

**Comment by maxstepanov** [comment]
The same thing we do every day, add objects and patch references. If the reference in the workload like, service accounts, pod disruption budget, topology spread i **must** be able to patch them. In order to generate the patch i need to know the object Kind to provided the appropriate patch.
 
Our Developers, **must** be able to specify the **service account**, **topology spread**, **pod disruption budget** etc in `score-k8s` via **resource**!
`score-k8s` doesn't support this pattern! Only for secrets and volumes!

I'm trying to avoid forking this, that's why i'm begging to add the value. so i can re-implement templating in CMD provider that also **leaves patches out-of-band**(score is not aware of them).

then i can use **wrap and dump** pattern. Where i wrap the `score-k8s` execution in a script that picks up the patches left by the my CMD provisioners and apply them to `manifests.yaml`

This is such a common devops pattern I'm really surprised to get so much push back on this.

**Comment by astromechza** [comment]
@maxstepanov let's keep the patching conversion in #25 please :) This issue is just about passing the "kind" through to to provisioner.

If you need to modify the behavior of the provisioner, I recommend you use the `params` section, for example:

```
resources:
  my-thing:
    type: example
    params:
      kind: something
```

These params are passed to the provisioner and should be used to modify it's output. This would apply just the same to the a provisioner that generates a "patch". The `class` field on a resource may also be used for this purpose.

I'm going to close this issue, and copy your comment above over to the thread on #25.

**Comment by maxstepanov** [comment]
@astromechza so resource polymorphism in the context of different kinds is not a desirable?
I'd like to generate different manifests for different workload Kinds but there is no way to do that now.
What wrong with this approach?

**Comment by astromechza** [comment]
The reason for this is that resources can be shared between multiple workloads. Since multiple workloads can be different "kinds", the patch/update generated by the provisioner may not work with one of the workloads. So implicit polymorphism is not desired since it can easily fail in these cases. The solution is to make the polymorphism _explicit_ and use the params or class.
